package accessplan

import (
	"fmt"
	"strings"
	"time"

	"github.com/systeampl/sshmgr/internal/access"
)

// RenderAnsible emits an auditable GitOps playbook with the same byte-digest
// precondition and grant-scoped markers as the native apply engine.
func RenderAnsible(plan *Plan) (string, error) {
	if err := Validate(plan, time.Time{}); err != nil {
		return "", err
	}
	var out strings.Builder
	fmt.Fprintf(&out, "---\n# generated by sshmgr from %s\n# immutable digest: %s\n", plan.PlanID, plan.Digest)
	for _, change := range plan.Changes {
		fmt.Fprintf(&out, "- name: %s · %s\n  hosts: %s\n  gather_facts: false\n  become: true\n  tasks:\n", yamlString(change.Host), yamlString(change.Account), yamlString(change.Host))
		command := fmt.Sprintf("if test -f %s; then sha256sum %s | awk '{print \"SHA256:\"$1}'; else printf %s; fi", shellString(change.Path), shellString(change.Path), shellString(access.ContentDigest(nil)))
		fmt.Fprintf(&out, "    - name: Verify immutable authorized_keys baseline\n      ansible.builtin.shell: %s\n      register: sshmgr_baseline\n      changed_when: false\n      failed_when: sshmgr_baseline.stdout != %s\n", yamlString(command), yamlString(change.PreconditionSHA256))
		for _, operation := range change.Operations {
			if operation.Action == "add" {
				line := strings.TrimSpace(operation.PublicKey) + " " + operation.Marker
				fmt.Fprintf(&out, "    - name: Add managed grant %s\n      ansible.builtin.lineinfile:\n        path: %s\n        line: %s\n        create: true\n        mode: %s\n", yamlString(operation.GrantID), yamlString(change.Path), yamlString(line), yamlString(planMode(change.Mode)))
			} else {
				regexp := `(^|\\s)` + operation.Marker + `(\\s|$)`
				fmt.Fprintf(&out, "    - name: Remove managed grant %s only\n      ansible.builtin.lineinfile:\n        path: %s\n        regexp: %s\n        state: absent\n", yamlString(operation.GrantID), yamlString(change.Path), yamlString(regexp))
			}
		}
	}
	return out.String(), nil
}

func yamlString(value string) string  { return "'" + strings.ReplaceAll(value, "'", "''") + "'" }
func shellString(value string) string { return "'" + strings.ReplaceAll(value, "'", "'\"'\"'") + "'" }
func planMode(value string) string {
	value = strings.TrimPrefix(value, "0")
	if value == "" {
		return "0600"
	}
	return "0" + value
}
