// Package ansible bridges sshmgr's host config to Ansible: it renders an
// inventory from resolved hosts and builds the argv for `ansible-playbook`.
// sshmgr owns inventory and targeting; Ansible owns playbook execution.
//
// The renderers are pure functions (no Ansible runtime needed) so they are
// unit-tested directly. The headline value is that sshmgr already knows the
// awkward parts — bastion chains, proxy_command, per-host quirks — and emits
// an inventory where hard-to-reach hosts work without a hand-kept inventory.
package ansible

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"sshmgr/internal/config"

	"gopkg.in/yaml.v3"
)

const header = "# Ansible inventory generated by sshmgr — do not hand-edit.\n"
const externalNote = "# external hosts: connection is left to your ~/.ssh/config" +
	" (proxy / Match / ControlMaster are not translated).\n"

// Inventory renders an Ansible inventory for aliases (already selected and
// resolved by the caller) in "yaml" (default) or "ini" format.
func Inventory(cfg *config.Config, aliases []string, format string) (string, error) {
	if format == "" {
		format = "yaml"
	}
	if format != "yaml" && format != "ini" {
		return "", fmt.Errorf("unknown inventory format %q (use yaml or ini)", format)
	}

	vars := map[string]map[string]any{}
	groups := map[string][]string{}
	ordered := make([]string, 0, len(aliases))
	hasExternal := false
	for _, a := range aliases {
		h, ok := cfg.ResolveHost(a)
		if !ok {
			continue
		}
		if h.External {
			hasExternal = true
		}
		hv, err := varsFor(cfg, h)
		if err != nil {
			return "", fmt.Errorf("host %q: %w", a, err)
		}
		vars[a] = hv
		groups[a] = groupsFor(h)
		ordered = append(ordered, a)
	}
	sort.Strings(ordered)

	head := header
	if hasExternal {
		head += externalNote
	}
	if format == "ini" {
		return head + renderINI(ordered, vars, groups), nil
	}
	body, err := renderYAML(ordered, vars, groups)
	if err != nil {
		return "", err
	}
	return head + body, nil
}

// varsFor builds the Ansible variables for one resolved host. It errors only
// when the host's proxy_jump chain is broken (a cycle).
func varsFor(cfg *config.Config, h config.HostConfig) (map[string]any, error) {
	v := map[string]any{"ansible_host": h.Host}
	if h.User != "" {
		v["ansible_user"] = h.User
	}
	if h.Port != 0 && h.Port != 22 {
		v["ansible_port"] = h.Port
	}
	// External hosts depend on the user's ssh-config (Match, ControlMaster,
	// custom ProxyCommand). Translating their connection args would lose
	// that, so emit only plain vars and let Ansible's ssh use ~/.ssh/config.
	if h.External {
		return v, nil
	}
	if h.Key != "" {
		v["ansible_ssh_private_key_file"] = config.ExpandPath(h.Key)
	}
	args, err := sshCommonArgs(cfg, h)
	if err != nil {
		return nil, err
	}
	if args != "" {
		v["ansible_ssh_common_args"] = args
	}
	return v, nil
}

// groupsFor returns the inventory groups a host belongs to: its configured
// groups plus a `tag_<tag>` synthetic group for each tag that is not already
// a group name.
func groupsFor(h config.HostConfig) []string {
	inGroup := map[string]bool{}
	out := make([]string, 0, len(h.Groups))
	for _, g := range h.Groups {
		inGroup[g] = true
		out = append(out, g)
	}
	for _, t := range h.Tags {
		if !inGroup[t] {
			out = append(out, "tag_"+t)
		}
	}
	sort.Strings(out)
	return out
}

// sshCommonArgs builds the ansible_ssh_common_args string from a host's
// proxy and ssh_options. proxy_command takes precedence over proxy_jump,
// matching the rest of sshmgr. It errors on a proxy_jump cycle.
func sshCommonArgs(cfg *config.Config, h config.HostConfig) (string, error) {
	var parts []string
	if h.ProxyCommand != "" {
		parts = append(parts, "-o", `ProxyCommand="`+h.ProxyCommand+`"`)
	} else if h.ProxyJump != "" {
		chain, err := resolveJumpChain(cfg, h.ProxyJump, map[string]bool{})
		if err != nil {
			return "", err
		}
		if chain != "" {
			parts = append(parts, "-o", "ProxyJump="+chain)
		}
	}
	for _, opt := range h.SSHOptions {
		if opt = normalizeOpt(opt); opt != "" {
			parts = append(parts, "-o", opt)
		}
	}
	return strings.Join(parts, " "), nil
}

// resolveJumpChain turns an sshmgr proxy_jump alias into an OpenSSH
// ProxyJump value — comma-separated hops, outermost first. A native host is
// expanded to a concrete user@host[:port]; an external jump host is kept as
// its ssh-config alias (and the chain stops there) so its ssh-config
// semantics — Match, ControlMaster, a custom ProxyCommand — survive; an
// alias that is not a configured host is passed through verbatim. A repeated
// alias means a config cycle and is reported as an error rather than
// silently dropped.
func resolveJumpChain(cfg *config.Config, alias string, seen map[string]bool) (string, error) {
	if alias == "" {
		return "", nil
	}
	if seen[alias] {
		return "", fmt.Errorf("proxy_jump cycle detected at %q", alias)
	}
	seen[alias] = true
	h, ok := cfg.ResolveHost(alias)
	if !ok {
		return alias, nil // not a configured host — assume an ssh-config alias
	}
	// An external jump host is reachable through the user's ssh-config;
	// reference it by alias and stop — ssh-config owns the rest of its chain.
	if h.External {
		return h.Host, nil
	}
	hop := jumpSpec(h)
	if h.ProxyJump != "" {
		upstream, err := resolveJumpChain(cfg, h.ProxyJump, seen)
		if err != nil {
			return "", err
		}
		if upstream != "" {
			return upstream + "," + hop, nil
		}
	}
	return hop, nil
}

// jumpSpec renders a host as an OpenSSH jump target: [user@]host[:port].
func jumpSpec(h config.HostConfig) string {
	s := h.Host
	if h.User != "" {
		s = h.User + "@" + s
	}
	if h.Port != 0 && h.Port != 22 {
		s += ":" + strconv.Itoa(h.Port)
	}
	return s
}

// normalizeOpt strips an optional "-o " prefix so "KEY=VAL" and "-o KEY=VAL"
// both reduce to "KEY=VAL".
func normalizeOpt(opt string) string {
	opt = strings.TrimSpace(opt)
	opt = strings.TrimPrefix(opt, "-o ")
	opt = strings.TrimPrefix(opt, "-o")
	return strings.TrimSpace(opt)
}

func renderYAML(aliases []string, vars map[string]map[string]any, groups map[string][]string) (string, error) {
	hostsNode := map[string]any{}
	for _, a := range aliases {
		hostsNode[a] = vars[a]
	}
	all := map[string]any{"hosts": hostsNode}

	children := map[string]any{}
	for _, a := range aliases {
		for _, g := range groups[a] {
			grp, ok := children[g].(map[string]any)
			if !ok {
				grp = map[string]any{"hosts": map[string]any{}}
				children[g] = grp
			}
			grp["hosts"].(map[string]any)[a] = nil
		}
	}
	if len(children) > 0 {
		all["children"] = children
	}

	out, err := yaml.Marshal(map[string]any{"all": all})
	if err != nil {
		return "", fmt.Errorf("marshal inventory: %w", err)
	}
	return string(out), nil
}

func renderINI(aliases []string, vars map[string]map[string]any, groups map[string][]string) string {
	groupHosts := map[string][]string{}
	var ungrouped []string
	for _, a := range aliases {
		if len(groups[a]) == 0 {
			ungrouped = append(ungrouped, a)
			continue
		}
		for _, g := range groups[a] {
			groupHosts[g] = append(groupHosts[g], a)
		}
	}

	emitted := map[string]bool{}
	var b strings.Builder
	for _, g := range sortedKeys(groupHosts) {
		b.WriteString("[" + g + "]\n")
		hs := append([]string{}, groupHosts[g]...)
		sort.Strings(hs)
		for _, a := range hs {
			b.WriteString(iniHostLine(a, vars[a], emitted))
		}
		b.WriteString("\n")
	}
	if len(ungrouped) > 0 {
		sort.Strings(ungrouped)
		b.WriteString("[ungrouped]\n")
		for _, a := range ungrouped {
			b.WriteString(iniHostLine(a, vars[a], emitted))
		}
	}
	return b.String()
}

// iniHostLine writes a host's full var line the first time the host is seen
// and a bare alias on later group memberships (Ansible merges by hostname).
func iniHostLine(alias string, vars map[string]any, emitted map[string]bool) string {
	if emitted[alias] {
		return alias + "\n"
	}
	emitted[alias] = true
	var b strings.Builder
	b.WriteString(alias)
	for _, k := range sortedKeys(vars) {
		b.WriteString(" " + k + "=" + iniValue(vars[k]))
	}
	b.WriteString("\n")
	return b.String()
}

// iniValue formats an INI host-var value, single-quoting it when it contains
// whitespace or quotes (e.g. an ansible_ssh_common_args string).
func iniValue(v any) string {
	s := fmt.Sprint(v)
	if strings.ContainsAny(s, " \t'\"") {
		return "'" + s + "'"
	}
	return s
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// PlaybookOptions are the pass-through knobs for `ansible-playbook`.
type PlaybookOptions struct {
	Check     bool
	Diff      bool
	Limit     string
	ExtraVars []string
}

// PlaybookArgv builds the argv (after the ansible-playbook binary) for
// running playbook against the generated inventory file.
func PlaybookArgv(playbook, inventoryPath string, opts PlaybookOptions) []string {
	argv := []string{"-i", inventoryPath}
	if opts.Check {
		argv = append(argv, "--check")
	}
	if opts.Diff {
		argv = append(argv, "--diff")
	}
	if opts.Limit != "" {
		argv = append(argv, "--limit", opts.Limit)
	}
	for _, ev := range opts.ExtraVars {
		argv = append(argv, "--extra-vars", ev)
	}
	return append(argv, playbook)
}

// ResolvePlaybook resolves a playbook argument: an existing path is used
// as-is; otherwise a bare name (no path separator) is looked up under
// playbooksDir.
func ResolvePlaybook(arg, playbooksDir string) (string, error) {
	if _, err := os.Stat(arg); err == nil {
		return arg, nil
	}
	if !strings.ContainsAny(arg, "/\\") {
		cand := filepath.Join(playbooksDir, arg)
		if _, err := os.Stat(cand); err == nil {
			return cand, nil
		}
	}
	return "", fmt.Errorf("playbook %q not found (also looked under %s)", arg, playbooksDir)
}

// DiscoverPlaybooks returns the *.yml / *.yaml file names in dir, sorted. A
// missing directory yields an empty list rather than an error — used by both
// the CLI and (later) the TUI playbook picker.
func DiscoverPlaybooks(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	var out []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		if n := e.Name(); strings.HasSuffix(n, ".yml") || strings.HasSuffix(n, ".yaml") {
			out = append(out, n)
		}
	}
	sort.Strings(out)
	return out, nil
}
